# Generated by Django 5.2.5 on 2025-10-28 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inviter_username", models.CharField(db_index=True, max_length=150)),
                ("invitee_username", models.CharField(db_index=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_confirmed", models.BooleanField(db_index=True, default=False)),
                (
                    "invitee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "邀请",
                "verbose_name_plural": "邀请",
                "db_table": "invitations",
                "indexes": [
                    models.Index(
                        fields=["inviter"], name="invitations_inviter_e51769_idx"
                    ),
                    models.Index(
                        fields=["invitee"], name="invitations_invitee_c9b489_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="invitations_created_acaa38_idx"
                    ),
                    models.Index(
                        fields=["is_confirmed"], name="invitations_is_conf_6a5ef6_idx"
                    ),
                ],
                "unique_together": {("inviter", "invitee")},
            },
        ),
        migrations.CreateModel(
            name="UserServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=150)),
                (
                    "server",
                    models.CharField(
                        choices=[("a", "A区"), ("b", "B区")],
                        db_index=True,
                        default="a",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_server",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户服务区",
                "verbose_name_plural": "用户服务区",
                "db_table": "user_servers",
                "indexes": [
                    models.Index(
                        fields=["server"], name="user_server_server_07d850_idx"
                    )
                ],
            },
        ),
    ]
