# Generated by Django 5.2.5 on 2025-11-05 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invitation",
            name="invitations_inviter_e51769_idx",
        ),
        migrations.RemoveIndex(
            model_name="invitation",
            name="invitations_invitee_c9b489_idx",
        ),
        migrations.RemoveIndex(
            model_name="invitation",
            name="invitations_is_conf_6a5ef6_idx",
        ),
        migrations.RenameIndex(
            model_name="invitation",
            new_name="invitation__created_44a34d_idx",
            old_name="invitations_created_acaa38_idx",
        ),
        migrations.RenameIndex(
            model_name="userserver",
            new_name="invitation__server_eea630_idx",
            old_name="user_server_server_07d850_idx",
        ),
        migrations.AddField(
            model_name="invitation",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["inviter", "created_at"], name="invitation__inviter_cae125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["invitee", "created_at"], name="invitation__invitee_421fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["inviter", "is_confirmed"],
                name="invitation__inviter_db2e1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["invitee", "is_confirmed"],
                name="invitation__invitee_defef6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["is_confirmed", "created_at"],
                name="invitation__is_conf_fd1e76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userserver",
            index=models.Index(
                fields=["server", "created_at"], name="invitation__server_699ed4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userserver",
            index=models.Index(
                fields=["username"], name="invitation__usernam_e92c64_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="invitation",
            table="invitation_invitation",
        ),
        migrations.AlterModelTable(
            name="userserver",
            table="invitation_userserver",
        ),
    ]
