# Generated by Django 5.2.6 on 2025-09-30 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("draw", "Draw"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("score_black", models.DecimalField(decimal_places=2, max_digits=5)),
                ("score_white", models.DecimalField(decimal_places=2, max_digits=5)),
                ("komi", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "games",
            },
        ),
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.PositiveSmallIntegerField(db_index=True)),
                ("col", models.PositiveSmallIntegerField(db_index=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("empty", "Empty"),
                        ],
                        default="empty",
                        max_length=10,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intersections",
                        to="datab.game",
                    ),
                ),
            ],
            options={
                "db_table": "intersections",
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player1", "player2"], name="games_player1_e692ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["created_at"], name="games_created_51ed57_idx"),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(
                fields=["game", "row", "col"], name="intersectio_game_id_cbeea2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intersection",
            unique_together={("game", "row", "col")},
        ),
    ]
