# Generated by Django 5.2.6 on 2025-10-04 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intersection",
            name="placed_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(
                fields=["game", "placed_at"], name="intersectio_game_id_002c61_idx"
            ),
        ),
    ]
