# Generated by Django 5.2.5 on 2025-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datab", "0002_intersection_placed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.CharField(
                blank=True,
                choices=[("black", "Black"), ("white", "White"), ("draw", "Draw")],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
    ]
