# Generated by Django 5.2.5 on 2025-11-05 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datab", "0003_alter_game_winner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"verbose_name": "游戏", "verbose_name_plural": "游戏"},
        ),
        migrations.AlterModelOptions(
            name="intersection",
            options={"verbose_name": "落子位置", "verbose_name_plural": "落子位置"},
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="datab_game_player1_40cc3f_idx",
            old_name="games_player1_e692ba_idx",
        ),
        migrations.RenameIndex(
            model_name="game",
            new_name="datab_game_created_4d95d1_idx",
            old_name="games_created_51ed57_idx",
        ),
        migrations.RenameIndex(
            model_name="intersection",
            new_name="datab_inter_game_id_fc7c82_idx",
            old_name="intersectio_game_id_cbeea2_idx",
        ),
        migrations.RenameIndex(
            model_name="intersection",
            new_name="datab_inter_game_id_86e04c_idx",
            old_name="intersectio_game_id_002c61_idx",
        ),
        migrations.AddField(
            model_name="game",
            name="is_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="intersection",
            name="move_number",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player1", "created_at"], name="datab_game_player1_ea0430_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["player2", "created_at"], name="datab_game_player2_3215b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["is_completed", "created_at"],
                name="datab_game_is_comp_756a64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["winner", "created_at"], name="datab_game_winner_2617bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(
                fields=["game", "move_number"], name="datab_inter_game_id_c034bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(
                fields=["color", "placed_at"], name="datab_inter_color_f3e313_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="game",
            table="datab_game",
        ),
        migrations.AlterModelTable(
            name="intersection",
            table="datab_intersection",
        ),
    ]
